import type { ReactNode } from "react";
import type { DeepAnalysisFact, DeepAnalysisOutput, DeepAnalysisResult, TimelineEvidence, TimelineExecutiveSynthesis, TimelineSynthesisItem } from "./types";
import { useI18n, type TFunction } from "../i18n";

export function AnalysisResult({ result, onReset }: { result: DeepAnalysisResult; onReset: () => void }) {
  const { t } = useI18n();
  const output = result.output;
  if (!output) return <section className="deep-result-empty product-panel"><h3>{result.status}</h3><p>{t("deepAnalysis.noOutput")}</p><button onClick={onReset}>{t("deepAnalysis.resultBack")}</button></section>;
  const safeOutput = normalizeOutput(output, t);
  const high = safeOutput.safety.analysisContextMode === "high_fidelity_identity_redacted";
  return <section className="deep-analysis-result"><header className="deep-result-header product-panel"><div><span>{safeOutput.templateCode} · v{safeOutput.templateVersion}</span><h2>{safeOutput.title}</h2><p>{safeOutput.executiveSummary}</p></div><div><strong>{safeOutput.confidence?.level || t("deepAnalysis.unavailableValue")}</strong><span>{t("deepAnalysis.confidence")}</span><button onClick={onReset}>{t("deepAnalysis.clearResult")}</button></div></header>
    <ResultSection title={`1. ${t("deepAnalysis.managementConclusion")}`}><p>{safeOutput.executiveSummary}</p></ResultSection>
    <ResultSection title={`2. ${t("deepAnalysis.crmFacts")}`}><FactGrid items={safeOutput.crmFacts} /></ResultSection>
    <ResultSection title={`3. ${high ? t("deepAnalysis.timelineHighFidelity") : t("deepAnalysis.timelineAnalysis")}`}><TimelineExecutiveSection synthesis={safeOutput.timelineExecutiveSynthesis} evidence={safeOutput.timelineEvidence} highFidelity={high} /></ResultSection>
    <UnavailableSection title={`4. ${t("deepAnalysis.customerHistory")}`} message={t("deepAnalysis.crmHistoryMissing")} />
    <UnavailableSection title={`5. ${t("deepAnalysis.externalFacts")}`} message={t("deepAnalysis.externalMissing")} />
    <ResultSection title={`6. ${t("deepAnalysis.aiInference")}`}><div className="deep-inference-list">{safeOutput.aiInferences.map((item, index) => <article key={item.statement || `inference-${index}`}><span>{item.label || t("deepAnalysis.inferenceLabel")}</span><p>{item.statement || t("deepAnalysis.noVerifiedInference")}</p></article>)}</div></ResultSection>
    <ResultSection title={`7. ${t("deepAnalysis.riskOpportunity")}`}><div className="deep-risk-opportunity"><section><h3>{t("deepAnalysis.risk")}</h3>{safeOutput.risks.length ? <ul>{safeOutput.risks.map((item) => <li key={item}>{item}</li>)}</ul> : <p>{t("deepAnalysis.noBlocker")}</p>}</section><section><h3>{t("deepAnalysis.opportunity")}</h3>{safeOutput.opportunities.length ? <ul>{safeOutput.opportunities.map((item) => <li key={item}>{item}</li>)}</ul> : <p>{t("deepAnalysis.noOpportunity")}</p>}</section></div></ResultSection>
    <ResultSection title={`8. ${t("deepAnalysis.scenario")}`}><div className="deep-scenario-grid">{safeOutput.scenarios.map((item, index) => <article key={item.name || `scenario-${index}`}><span>{item.direction || t("deepAnalysis.unavailableValue")}</span><h3>{item.name || t("deepAnalysis.noNamedScenario")}</h3><p>{item.summary || t("deepAnalysis.noScenarioContent")}</p></article>)}</div></ResultSection>
    <ResultSection title={`9. ${t("deepAnalysis.recommendedActions")}`}><div className="deep-action-list">{safeOutput.recommendedActions.map((item, index) => <article key={item.action || `action-${index}`}><header><h3>{item.action || t("deepAnalysis.noAction")}</h3><span>{item.status || t("deepAnalysis.draftOnly")}</span></header><p>{item.reason || t("deepAnalysis.noVerifiedActionBasis")}</p><dl><dt>{t("deepAnalysis.pendingRole")}</dt><dd>{item.suggestedRole || t("deepAnalysis.pendingRole")}</dd><dt>{t("deepAnalysis.pendingWindow")}</dt><dd>{item.suggestedHorizon || t("deepAnalysis.pendingWindow")}</dd><dt>{t("deepAnalysis.actualSources")}</dt><dd>{item.source || t("deepAnalysis.unavailableValue")}</dd></dl></article>)}</div></ResultSection>
    <ResultSection title={`10. ${t("deepAnalysis.limitations")}`}><ul>{safeOutput.limitations.map((item) => <li key={item}>{item}</li>)}</ul></ResultSection>
    <ResultSection title={`11. ${t("deepAnalysis.sourcesSafety")}`}><div className="deep-source-grid"><SourceSummary sources={safeOutput.sources} /><section><h3>{t("deepAnalysis.unconnectedSources")}</h3><p>{t("deepAnalysis.crmHistoryMissing")}</p><p>{t("deepAnalysis.externalMissing")}</p><p>{t("deepAnalysis.internalMissing")}</p></section><section><h3>{t("deepAnalysis.modelSafety")}</h3><p>Provider：{safeOutput.provider?.used || t("deepAnalysis.unavailableValue")}</p><p>{t("deepAnalysis.externalCall")}：{safeOutput.provider ? safeOutput.provider.externalModelCalled ? t("deepAnalysis.yes") : t("deepAnalysis.no") : t("deepAnalysis.unavailableValue")}</p><p>{high ? t("deepAnalysis.crmOriginalSent") : t("deepAnalysis.structuredTimelineUsed")}</p><p>{high ? t("deepAnalysis.timelineOriginalSent") : t("deepAnalysis.timelineOriginalNotSent")}</p><p>{high ? t("deepAnalysis.exactAmountSentHigh") : t("deepAnalysis.exactAmountSent")}</p><p>{t("deepAnalysis.crmWriteback")}</p></section></div></ResultSection>
  </section>;
}

function ResultSection({ title, children }: { title: string; children: ReactNode }) { return <section className="deep-result-section product-panel"><h2>{title}</h2>{children}</section>; }
function UnavailableSection({ title, message }: { title: string; message: string }) { const { t } = useI18n(); return <ResultSection title={title}><div className="deep-unavailable"><strong>{message}</strong><p>{t("deepAnalysis.dependenciesBody")}</p></div></ResultSection>; }
function FactGrid({ items }: { items: DeepAnalysisOutput["crmFacts"] }) {
  const { t } = useI18n();
  const description = items.find((item) => item.label.toLowerCase().includes("description")) || items[0];
  if (!description) return <p>{t("deepAnalysis.noVerifiedFact")}</p>;
  return <div className="deep-fact-overview">
    <article className="deep-fact-summary"><span>{t("deepAnalysis.factLabel")}</span><strong>{t("deepAnalysis.descriptionPreview")}</strong><small>{t("deepAnalysis.crmOriginalNotice")}</small><p>{description.value || t("deepAnalysis.noVerifiedFact")}</p></article>
    <details className="deep-fact-details"><summary>{t("deepAnalysis.viewAllFacts", { count: items.length })}</summary><div className="deep-fact-detail-grid">{items.map((item, index) => <article key={item.source || `fact-${index}`}><header><span>{t("deepAnalysis.factLabel")}</span><strong>{item.label || t("deepAnalysis.unavailableValue")}</strong></header><p>{item.value || t("deepAnalysis.noVerifiedFact")}</p><details className="deep-technical-sources"><summary>{t("deepAnalysis.technicalSources")}</summary><code>{item.source || t("deepAnalysis.unavailableValue")}</code></details></article>)}</div></details>
  </div>;
}

function SourceSummary({ sources }: { sources: DeepAnalysisOutput["sources"] }) {
  const { t } = useI18n();
  const groups = groupSources(sources);
  const uniqueSources = Array.from(new Map(sources.map((item) => [`${item.type}|${item.ref}`, item])).values());
  return <section className="deep-source-summary"><h3>{t("deepAnalysis.actualSources")}</h3><div className="deep-source-group-list">{groups.map((group) => <p key={group.type}><strong>{group.type || t("deepAnalysis.unavailableValue")}</strong><span>{t("deepAnalysis.sourceItems", { count: group.count })}</span></p>)}</div><details className="deep-source-details"><summary>{t("deepAnalysis.viewSourceDetails", { count: uniqueSources.length })}</summary><div className="deep-source-reference-grid">{uniqueSources.map((item, index) => <article key={`${item.type}-${item.ref || index}`}><strong>{item.type || t("deepAnalysis.unavailableValue")}</strong><code>{item.ref || t("deepAnalysis.unavailableValue")}</code></article>)}</div></details></section>;
}

function groupSources(sources: DeepAnalysisOutput["sources"]) {
  const counts = new Map<string, number>();
  for (const item of sources) counts.set(item.type, (counts.get(item.type) || 0) + 1);
  return Array.from(counts, ([type, count]) => ({ type, count }));
}
function TimelineExecutiveSection({ synthesis, evidence, highFidelity = false }: { synthesis: TimelineExecutiveSynthesis; evidence: TimelineEvidence[]; highFidelity?: boolean }) {
  const { t } = useI18n();
  return <div className="timeline-executive-synthesis">
    <section className="timeline-executive-conclusion"><span>{t("deepAnalysis.managementConclusion")}</span><strong>{synthesis.overallConclusion}</strong><p>{synthesis.momentumTrend.statement} {synthesis.customerPosition.statement}</p></section>
    <div className="timeline-synthesis-grid">
      <SynthesisBlock title={t("deepAnalysis.customerDynamics")}><p>{synthesis.customerPosition.statement}</p><p>{synthesis.decisionClarity.statement}</p><p>{synthesis.stakeholderDynamics.statement}</p></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.momentum")}><strong>{synthesis.momentumTrend.statement}</strong></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.keyThemes")}><SynthesisList items={synthesis.keyThemes} empty={t("deepAnalysis.noStableTheme")} /></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.blockers")}><SynthesisList items={synthesis.topBlockers} empty={t("deepAnalysis.noBlocker")} /></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.commitmentGap")}><p>{synthesis.commitmentSummary.statement}</p><small>{t("deepAnalysis.commitmentCount", { made: synthesis.commitmentSummary.madeCount, completed: synthesis.commitmentSummary.completedCount, open: synthesis.commitmentSummary.openCount })}</small></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.contradictions")}><SynthesisList items={synthesis.contradictions} empty={t("deepAnalysis.noContradiction")} /></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.opportunitySignals")}><SynthesisList items={synthesis.opportunitySignals} empty={t("deepAnalysis.noOpportunity")} /></SynthesisBlock>
      <SynthesisBlock title={t("deepAnalysis.managementActions")}><SynthesisList items={synthesis.managementActions} empty={t("deepAnalysis.noAction")} /></SynthesisBlock>
    </div>
    <footer className="timeline-synthesis-meta"><span>{t("deepAnalysis.confidence")}：{synthesis.confidence.level}</span><span>{t("deepAnalysis.coverage")}：{synthesis.coverage.level}</span><span>{t("deepAnalysis.events", { count: synthesis.coverage.eventCount, evidence: synthesis.coverage.representativeEvidenceCount })}</span></footer>
    <details className="timeline-evidence-details"><summary>{highFidelity ? t("deepAnalysis.redactedBasis") : t("deepAnalysis.analysisBasis")}（{t("deepAnalysis.representativeEvidence", { count: evidence.length })}）</summary><div className="timeline-evidence-list">{evidence.map((item, index) => <article key={item.evidenceToken || `evidence-${index}`}><header><span>{item.relativeTime || t("deepAnalysis.relativeDateMissing")}</span><strong>{item.activityType || t("deepAnalysis.activityTypeMissing")}</strong></header><p>{item.summary || t("deepAnalysis.noVerifiedEvidence")}</p><small>{t("deepAnalysis.supports")}：{item.supports.length ? item.supports.join("、") : t("deepAnalysis.comprehensiveJudgment")}</small><code>{item.evidenceToken || t("deepAnalysis.evidenceTokenMissing")}</code></article>)}</div></details>
    {synthesis.limitations.length ? <p className="timeline-synthesis-limitations">{t("deepAnalysis.limitation", { items: synthesis.limitations.join("；") })}</p> : null}
  </div>;
}

function SynthesisBlock({ title, children }: { title: string; children: ReactNode }) { return <section className="timeline-synthesis-block"><h3>{title}</h3>{children}</section>; }
function SynthesisList({ items, empty }: { items: TimelineSynthesisItem[]; empty: string }) { const { t } = useI18n(); return items.length ? <ul>{items.map((item, index) => <li key={item.code || `synthesis-${index}`}><strong>{item.label || item.statement || t("deepAnalysis.noVerifiedContent")}</strong>{item.status ? <span>{item.status}</span> : null}{item.label && item.statement ? <p>{item.statement}</p> : null}</li>)}</ul> : <p className="timeline-empty-note">{empty}</p>; }

function normalizeOutput(output: DeepAnalysisOutput, t: TFunction): DeepAnalysisOutput {
  return { ...output, crmFacts: normalizeFacts(output.crmFacts, t), timelineFacts: normalizeFacts(output.timelineFacts, t), timelineFindings: records(output.timelineFindings).map((item) => ({ label: stringValue(item.label, t("deepAnalysis.unavailableValue")), statement: stringValue(item.statement, t("deepAnalysis.noVerifiedContent")), evidenceRefs: stringArray(item.evidenceRefs) })), timelineExecutiveSynthesis: normalizeSynthesis(output.timelineExecutiveSynthesis, t), timelineEvidence: normalizeEvidence(output.timelineEvidence, t), customerHistoryFacts: normalizeFacts(output.customerHistoryFacts, t), externalFacts: normalizeFacts(output.externalFacts, t), internalCapabilityFacts: normalizeFacts(output.internalCapabilityFacts, t), aiInferences: records(output.aiInferences).map((item) => ({ label: stringValue(item.label, t("deepAnalysis.inferenceLabel")), statement: stringValue(item.statement, t("deepAnalysis.noVerifiedInference")), evidenceRefs: stringArray(item.evidenceRefs) })), risks: stringArray(output.risks), opportunities: stringArray(output.opportunities), scenarios: records(output.scenarios).map((item) => ({ name: stringValue(item.name, t("deepAnalysis.noNamedScenario")), direction: stringValue(item.direction, t("deepAnalysis.unavailableValue")), summary: stringValue(item.summary, t("deepAnalysis.noScenarioContent")) })), recommendedActions: records(output.recommendedActions).map((item) => ({ action: stringValue(item.action, t("deepAnalysis.noAction")), reason: stringValue(item.reason, t("deepAnalysis.noVerifiedActionBasis")), suggestedRole: stringValue(item.suggestedRole, t("deepAnalysis.pendingRole")), suggestedHorizon: stringValue(item.suggestedHorizon, t("deepAnalysis.pendingWindow")), evidenceRefs: stringArray(item.evidenceRefs), source: stringValue(item.source, t("deepAnalysis.unavailableValue")), status: stringValue(item.status, t("deepAnalysis.draftOnly")) })), limitations: stringArray(output.limitations), sources: records(output.sources).map((item) => ({ type: stringValue(item.type, t("deepAnalysis.unavailableValue")), ref: stringValue(item.ref, t("deepAnalysis.unavailableValue")) })) };
}

function normalizeFacts(value: unknown, t: TFunction): DeepAnalysisFact[] { return records(value).map((item) => ({ label: stringValue(item.label, t("deepAnalysis.unavailableValue")), value: stringValue(item.value, t("deepAnalysis.noVerifiedFact")), source: stringValue(item.source, t("deepAnalysis.unavailableValue")), sourceType: "crm_current" })); }
function normalizeEvidence(value: unknown, t: TFunction): TimelineEvidence[] { return records(value).map((item) => ({ evidenceToken: stringValue(item.evidenceToken, ""), relativeTime: stringValue(item.relativeTime, t("deepAnalysis.relativeDateMissing")), activityType: stringValue(item.activityType, t("deepAnalysis.activityTypeMissing")), summary: stringValue(item.summary, t("deepAnalysis.noVerifiedEvidence")), supports: stringArray(item.supports) })); }
function normalizeSynthesis(value: unknown, t: TFunction): TimelineExecutiveSynthesis {
  const source = record(value);
  const branch = (key: string) => { const item = record(source[key]); return { code: stringValue(item.code, "UNAVAILABLE"), statement: stringValue(item.statement, t("deepAnalysis.noVerifiedContent")) }; };
  const items = (key: string): TimelineSynthesisItem[] => records(source[key]).map((item, index) => ({ code: stringValue(item.code, `unavailable-${key}-${index}`), label: typeof item.label === "string" ? item.label : undefined, statement: typeof item.statement === "string" ? item.statement : undefined, count: typeof item.count === "number" ? item.count : undefined, evidenceTokens: stringArray(item.evidenceTokens), status: item.status === "Draft" ? "Draft" : undefined }));
  const commitment = record(source.commitmentSummary); const confidence = record(source.confidence); const coverage = record(source.coverage); const stakeholder = branch("stakeholderDynamics");
  return { overallConclusion: stringValue(source.overallConclusion, t("deepAnalysis.noVerifiedContent")), overallCode: stringValue(source.overallCode, "UNAVAILABLE"), momentumTrend: branch("momentumTrend"), customerPosition: branch("customerPosition"), decisionClarity: branch("decisionClarity"), stakeholderDynamics: { ...stakeholder, roles: stringArray(record(source.stakeholderDynamics).roles) }, keyThemes: items("keyThemes"), topBlockers: items("topBlockers"), commitmentSummary: { code: stringValue(commitment.code, "UNAVAILABLE"), statement: stringValue(commitment.statement, t("deepAnalysis.noVerifiedContent")), madeCount: numberValue(commitment.madeCount), completedCount: numberValue(commitment.completedCount), openCount: numberValue(commitment.openCount) }, contradictions: items("contradictions"), opportunitySignals: items("opportunitySignals"), managementActions: items("managementActions"), confidence: { level: stringValue(confidence.level, t("deepAnalysis.unavailableValue")), reason: stringValue(confidence.reason, t("deepAnalysis.noVerifiedContent")) }, coverage: { level: stringValue(coverage.level, t("deepAnalysis.unavailableValue")), activityCount: numberValue(coverage.activityCount), eventCount: numberValue(coverage.eventCount), representativeEvidenceCount: numberValue(coverage.representativeEvidenceCount) }, representativeEvidenceTokens: stringArray(source.representativeEvidenceTokens), limitations: stringArray(source.limitations), representativeEvidence: normalizeEvidence(source.representativeEvidence, t) };
}

function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function records(value: unknown): Record<string, unknown>[] { return Array.isArray(value) ? value.map(record).filter((item) => Object.keys(item).length > 0) : []; }
function stringValue(value: unknown, fallback: string): string { return typeof value === "string" && value.length > 0 ? value : fallback; }
function stringArray(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function numberValue(value: unknown): number { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
