import type { DeepAnalysisPreview, DeepAnalysisResult } from "./types";
import { useI18n } from "../i18n";

export function DeepAnalysisSafetyRail({ preview, result }: { preview: DeepAnalysisPreview | null; result: DeepAnalysisResult | null }) {
  const { t } = useI18n();
  const usedProvider = result?.output?.provider.used || preview?.provider || t("deepAnalysis.unavailableValue");
  const externalCalled = result?.output?.provider.externalModelCalled === true;
  const high = result?.output?.safety.analysisContextMode === "high_fidelity_identity_redacted" || preview?.analysisContextMode === "high_fidelity_identity_redacted";
  const sanitizedTimeline = result?.output?.safety.sanitizedTimelineEvidenceSent ?? preview?.sanitizedTimelineEvidenceSent ?? false;
  return <aside className="deep-safety-rail product-panel" aria-label={t("deepAnalysis.sourcesSafety")}><header><h3>{t("deepAnalysis.modelSafety")}</h3><span>{t("deepAnalysis.readOnly")}</span></header><dl><dt>{t("deepAnalysis.analysisContextMode")}</dt><dd>{high ? t("deepAnalysis.highFidelityMode") : t("deepAnalysis.standardMode")}</dd><dt>Safe Context</dt><dd>{t("deepAnalysis.enabled")}</dd>{high ? <><dt>{t("deepAnalysis.crmBusinessOriginalLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd><dt>{t("deepAnalysis.timelineBusinessOriginalLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd><dt>{t("deepAnalysis.exactAmountLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd><dt>{t("deepAnalysis.exactDateLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd><dt>{t("deepAnalysis.routeTermsLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd><dt>{t("deepAnalysis.customerIdentityLabel")}</dt><dd>{t("deepAnalysis.masked")}</dd><dt>{t("deepAnalysis.identityRedactedBusinessTextLabel")}</dt><dd>{t("deepAnalysis.sent")}</dd></> : <><dt>{t("deepAnalysis.crmBusinessOriginalLabel")}</dt><dd>{t("deepAnalysis.notSent")}</dd><dt>{t("deepAnalysis.timelineBusinessOriginalLabel")}</dt><dd>{t("deepAnalysis.notSent")}</dd><dt>{t("deepAnalysis.exactAmountLabel")}</dt><dd>{t("deepAnalysis.notSent")}</dd><dt>{t("deepAnalysis.exactDateLabel")}</dt><dd>{t("deepAnalysis.notSent")}</dd><dt>{t("deepAnalysis.customerIdentityLabel")}</dt><dd>{t("deepAnalysis.masked")}</dd><dt>{t("deepAnalysis.timelineEvidenceLabel")}</dt><dd>{sanitizedTimeline ? t("deepAnalysis.used") : t("deepAnalysis.noContent")}</dd></>}<dt>{t("deepAnalysis.crmWritebackLabel")}</dt><dd>{t("deepAnalysis.no")}</dd><dt>{t("deepAnalysis.providerLabel")}</dt><dd>{usedProvider}</dd><dt>{t("deepAnalysis.externalModelCallLabel")}</dt><dd>{externalCalled ? t("deepAnalysis.yes") : t("deepAnalysis.no")}</dd><dt>{t("deepAnalysis.schemaValidationLabel")}</dt><dd>{result?.schemaStatus || t("deepAnalysis.notRun")}</dd><dt>{t("deepAnalysis.safetyValidationLabel")}</dt><dd>{result?.safetyStatus || (preview ? t("deepAnalysis.pass") : t("deepAnalysis.notRun"))}</dd><dt>{t("deepAnalysis.citationValidationLabel")}</dt><dd>{result?.citationStatus || t("deepAnalysis.notRun")}</dd></dl>{preview ? <section><span>{t("deepAnalysis.safeContextHashLabel")}</span><code>{preview.safeContextHash}</code></section> : null}</aside>;
}
