import {
  bookingDepartmentOptions,
  budgetStatusOptions,
  caseStageOptions,
  customerNeedOptions,
  decisionMakerOptions,
  goodsHandledOptions,
  opportunityDetailTypeOptions,
  opportunityListOptions,
  opportunityTypeOptions,
  organizationGroupOptions,
  priorityOptions,
  projectSizeUnitOptions,
  proposalContentOptions,
  researchBackgroundOptions,
  salesDepartmentOptions,
  tradeTermsOptions,
  transportModeOptions,
  warehouseScaleOptions,
  winProbabilityOptions,
  yesNoOptions,
} from "./choiceOptions.mjs";

const labels = (zh, en, ja) => ({ "zh-CN": zh, "en-US": en, "ja-JP": ja });
const confirmed = (trial) => ({ company: true, trial });

export const opportunityFieldMapping = [
  field({
    appName: "opportunityName",
    sourceLabel: "案件名称",
    companyLogicalName: "name",
    trialLogicalName: "name",
    d365Name: "name",
    label: labels("案件名称", "Opportunity Name", "案件名"),
    type: "text",
    targetObject: "Opportunity",
    category: "basic",
    crmDataKey: "opportunity_name",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    notes: "可能包含客户或项目线索，进入 AI 前必须摘要化/脱敏。",
  }),
  field({
    appName: "customerRef",
    sourceLabel: "客户",
    companyLogicalName: "parentaccountid",
    trialLogicalName: "parentaccountid",
    d365Name: "_customerid_value",
    label: labels("客户", "Customer", "顧客"),
    type: "lookup",
    targetObject: "Account",
    category: "customer",
    crmDataKey: "customer_name",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: false,
    sensitivity: "confidential",
    safeTransform: "token",
    requiredForDemo: true,
    sourcePage: "Customer",
    notes: "AI 仅使用 customerToken，不传客户真实名称。",
  }),
  field({
    appName: "customerToken",
    sourceLabel: "客户 Token",
    companyLogicalName: "parentaccountid",
    trialLogicalName: null,
    d365Name: null,
    label: labels("客户 Token", "Customer Token", "顧客トークン"),
    type: "token",
    targetObject: "Account",
    category: "customer",
    sourceSystem: "ai_gateway",
    mappingStatus: "derived",
    realLogicalNameConfirmed: confirmed(false),
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "token",
    requiredForDemo: true,
    sourcePage: "AI Gateway",
  }),
  field({
    appName: "customerNameCn",
    sourceLabel: "客户名称(中国語)",
    companyLogicalName: null,
    trialLogicalName: "aigw_customernamecn",
    d365Name: "aigw_customernamecn",
    label: labels("客户名称(中国語)", "Customer Name (Chinese)", "顧客名（中国語）"),
    type: "text",
    targetObject: "Account",
    category: "customer",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: false,
    sensitivity: "confidential",
    safeTransform: "token",
    requiredForDemo: true,
    sourcePage: "Customer",
    notes: "仅用于 CRM Data 高还原展示；Safe Context 使用 customerToken。",
  }),
  field({
    appName: "statusReason",
    sourceLabel: "状态描述",
    companyLogicalName: "statuscode",
    trialLogicalName: "statuscode",
    d365Name: "statuscode",
    label: labels("状态描述", "Status Reason", "状態理由"),
    type: "choice",
    targetObject: "Opportunity",
    category: "basic",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    sourcePage: "Basic Information",
  }),
  field({
    appName: "opportunityType",
    sourceLabel: "案件类型",
    companyLogicalName: "new_bd_newexisting",
    trialLogicalName: "aigw_opportunitytype",
    d365Name: "aigw_opportunitytype",
    label: labels("案件类型", "Opportunity Type", "案件タイプ"),
    type: "choice",
    targetObject: "Opportunity",
    category: "basic",
    choiceOptions: opportunityTypeOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Basic Information",
  }),
  field({
    appName: "opportunityStage",
    sourceLabel: "案件状态",
    companyLogicalName: "new_status",
    trialLogicalName: "aigw_casestage",
    d365Name: "aigw_casestage",
    label: labels("案件状态", "Case Stage", "案件ステージ"),
    type: "choice",
    targetObject: "Opportunity",
    category: "salesProgress",
    choiceOptions: caseStageOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
  }),
  field({
    appName: "salesDepartment",
    sourceLabel: "销售部门",
    companyLogicalName: "new_bd_group",
    trialLogicalName: "aigw_salesdepartment_choice",
    d365Name: "aigw_salesdepartment_choice",
    label: labels("销售部门", "Sales Department", "営業部門"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "basic",
    choiceOptions: salesDepartmentOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_salesdepartment 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "bookingDepartment",
    sourceLabel: "计上部门",
    companyLogicalName: "new_related_department",
    trialLogicalName: "aigw_bookingdepartment_choice",
    d365Name: "aigw_bookingdepartment_choice",
    label: labels("计上部门", "Booking Department", "計上部門"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "basic",
    choiceOptions: bookingDepartmentOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_bookingdepartment 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "organizationGroup",
    sourceLabel: "组织团体",
    companyLogicalName: "new_organization_group",
    trialLogicalName: "aigw_organizationgroup_choice",
    d365Name: "aigw_organizationgroup_choice",
    label: labels("组织团体", "Organization Group", "組織団体"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "basic",
    choiceOptions: organizationGroupOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_organizationgroup 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "opportunityList",
    sourceLabel: "案件列表",
    companyLogicalName: "new_pipeline_list",
    trialLogicalName: "aigw_opportunitylist_bool",
    d365Name: "aigw_opportunitylist_bool",
    label: labels("案件列表", "Opportunity List", "案件リスト"),
    type: "yesNo",
    companyType: "boolean",
    trialType: "yesNo",
    targetObject: "Opportunity",
    category: "basic",
    choiceOptions: opportunityListOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    notes: "正式字段已切换到 replacement Yes/No。旧字段 aigw_opportunitylist 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "opportunityDetailType",
    sourceLabel: "案件详细信息",
    companyLogicalName: "new_bd_details",
    trialLogicalName: "aigw_opportunitydetailtype",
    d365Name: "aigw_opportunitydetailtype",
    label: labels("案件详细信息", "Opportunity Detail Type", "案件詳細"),
    type: "choice",
    targetObject: "Opportunity",
    category: "opportunityDetail",
    choiceOptions: opportunityDetailTypeOptions,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Opportunity Detail",
  }),
  field({
    appName: "startDateStatus",
    sourceLabel: "案件开始日",
    companyLogicalName: "new_startdate",
    trialLogicalName: "aigw_startdate",
    d365Name: "aigw_startdate",
    label: labels("案件开始日", "Case Start Date", "案件開始日"),
    type: "date",
    targetObject: "Opportunity",
    category: "basic",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "relativeDate",
    requiredForDemo: true,
    sourcePage: "Basic Information",
  }),
  field({
    appName: "opportunityPlace",
    sourceLabel: "案件场所",
    companyLogicalName: "new_location",
    trialLogicalName: "aigw_opportunitylocation",
    d365Name: "_aigw_opportunitylocation_value",
    label: labels("案件场所", "Opportunity Place", "案件場所"),
    type: "lookup",
    companyType: "lookup",
    trialType: "lookup",
    targetObject: "Opportunity",
    category: "basic",
    mappingStatus: "implemented_lookup",
    includeInSelect: false,
    includeInCrmData: true,
    includeInSafeContext: false,
    sensitivity: "business",
    safeTransform: "exclude",
    requiredForDemo: true,
    sourcePage: "Basic Information",
    replacementTrialLogicalName: "aigw_opportunitylocation",
    replacementType: "lookup",
    notes: "测试环境使用独立 Location lookup；该字段及旧 String 均不进入 Safe Context 或 Provider Payload。",
  }),
  field({
    appName: "sanitizedDescription",
    sourceLabel: "说明",
    companyLogicalName: "description",
    trialLogicalName: "description",
    d365Name: "description",
    label: labels("说明", "Description", "説明"),
    type: "multiline",
    targetObject: "Opportunity",
    category: "opportunityDetail",
    crmDataKey: "description",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    sourcePage: "Opportunity Detail",
    notes: "可能包含敏感内容，只允许 sanitize + summarize 后进入 AI。",
  }),
  field({
    appName: "sanitizedProgressSummary",
    sourceLabel: "案件进展摘要",
    companyLogicalName: null,
    trialLogicalName: "aigw_progresssummary",
    d365Name: "aigw_progresssummary",
    label: labels("案件进展摘要", "Progress Summary", "進捗要約"),
    type: "multiline",
    targetObject: "Opportunity",
    category: "opportunityDetail",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: false,
    sourcePage: "Opportunity Detail",
    notes: "仅保存合成脱敏进展摘要；不是 raw timeline。进入 AI 前继续执行 sanitize + summarize。",
  }),
  field({
    appName: "globalInitiative",
    sourceLabel: "全球倡议",
    companyLogicalName: "new_global_initiative_key",
    trialLogicalName: "aigw_globalinitiative",
    d365Name: "aigw_globalinitiative",
    label: labels("全球倡议", "Global Initiative", "グローバル施策"),
    type: "yesNo",
    targetObject: "Opportunity",
    category: "opportunityDetail",
    choiceOptions: yesNoOptions,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    sourcePage: "Opportunity Detail",
  }),
  field({
    appName: "cargoDescription",
    sourceLabel: "货物说明",
    companyLogicalName: "new_goods_handled",
    trialLogicalName: "aigw_goodshandled",
    d365Name: "aigw_goodshandled",
    label: labels("货物说明", "Goods Handled", "貨物説明"),
    type: "choice",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    crmDataKey: "cargo_type",
    choiceOptions: goodsHandledOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "volumeSize",
    sourceLabel: "案件物量规模",
    companyLogicalName: "new_project_size",
    trialLogicalName: "aigw_projectsize",
    d365Name: "aigw_projectsize",
    label: labels("案件物量规模", "Project Size", "物量規模"),
    type: "decimal",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    crmDataKey: "volume_size",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "band",
    requiredForDemo: true,
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "volumeUnit",
    sourceLabel: "案件物量规模单位",
    companyLogicalName: "new_project_size_unit",
    trialLogicalName: "aigw_projectsizeunit",
    d365Name: "aigw_projectsizeunit",
    label: labels("案件物量规模单位", "Project Size Unit", "物量単位"),
    type: "choice",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    choiceOptions: projectSizeUnitOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "warehouseScale",
    sourceLabel: "仓库规模",
    companyLogicalName: "new_warehouse_scale",
    trialLogicalName: "aigw_warehousescale",
    d365Name: "aigw_warehousescale",
    label: labels("仓库规模", "Warehouse Scale", "倉庫規模"),
    type: "choice",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    crmDataKey: "warehouse_scale",
    choiceOptions: warehouseScaleOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "band",
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "tradeTerms",
    sourceLabel: "贸易条件",
    companyLogicalName: "new_trade_terms",
    trialLogicalName: "aigw_tradeterms",
    d365Name: "aigw_tradeterms",
    label: labels("贸易条件", "Trade Terms", "貿易条件"),
    type: "choice",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    choiceOptions: tradeTermsOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "transportMode",
    sourceLabel: "运送模式",
    companyLogicalName: "new_transport_mode",
    trialLogicalName: "aigw_transportmode",
    d365Name: "aigw_transportmode",
    label: labels("运送模式", "Transport Mode", "輸送モード"),
    type: "choice",
    targetObject: "LogisticsRequirement",
    category: "logistics",
    crmDataKey: "transport_mode",
    choiceOptions: transportModeOptions,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "oneTimeOrContinuous",
    sourceLabel: "一次性/持续性",
    companyLogicalName: "new_spot_continuous",
    trialLogicalName: "aigw_spotcontinuous",
    d365Name: "aigw_spotcontinuous",
    label: labels("一次性/持续性", "Spot / Continuous", "一回/継続"),
    type: "yesNo",
    companyType: "boolean",
    trialType: "boolean",
    targetObject: "Opportunity",
    category: "logistics",
    crmDataKey: "recurring_type",
    choiceOptions: budgetStatusOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Logistics Requirement",
  }),
  field({
    appName: "priority",
    sourceLabel: "Priority",
    companyLogicalName: "new_priority",
    trialLogicalName: "aigw_priority_choice",
    d365Name: "aigw_priority_choice",
    label: labels("Priority", "Priority", "優先度"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "salesProgress",
    choiceOptions: priorityOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_priority 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "budgetStatus",
    sourceLabel: "是否预算内",
    companyLogicalName: "new_budgeted_or_not",
    trialLogicalName: "aigw_budgetstatus",
    d365Name: "aigw_budgetstatus",
    label: labels("是否预算内", "Budget Status", "予算内外"),
    type: "yesNo",
    targetObject: "Opportunity",
    category: "salesProgress",
    choiceOptions: budgetStatusOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
  }),
  field({
    appName: "researchBackground",
    sourceLabel: "调查背景",
    companyLogicalName: "new_background",
    trialLogicalName: "aigw_researchbackground_choice",
    d365Name: "aigw_researchbackground_choice",
    label: labels("调查背景", "Research Background", "調査背景"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "qualification",
    choiceOptions: researchBackgroundOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Qualification",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_researchbackground 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "decisionMakerStatus",
    sourceLabel: "决裁者",
    companyLogicalName: "new_decider",
    trialLogicalName: "aigw_decider_choice",
    d365Name: "aigw_decider_choice",
    label: labels("决裁者", "Decision Maker", "決裁者"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "qualification",
    choiceOptions: decisionMakerOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Qualification",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_decider 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "customerNeed",
    sourceLabel: "客户需求",
    companyLogicalName: "new_customerneed",
    trialLogicalName: "aigw_customerneed_choice",
    d365Name: "aigw_customerneed_choice",
    label: labels("客户需求", "Customer Need", "顧客ニーズ"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "qualification",
    crmDataKey: "customer_need",
    choiceOptions: customerNeedOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "Qualification",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_customerneed 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "proposalContent",
    sourceLabel: "提案内容",
    companyLogicalName: "new_proposedsolution",
    trialLogicalName: "aigw_proposalcontent_choice",
    d365Name: "aigw_proposalcontent_choice",
    label: labels("提案内容", "Proposal Content", "提案内容"),
    type: "choice",
    companyType: "optionset",
    trialType: "choice",
    targetObject: "Opportunity",
    category: "qualification",
    crmDataKey: "proposal_content",
    choiceOptions: proposalContentOptions,
    mappingStatus: "active_after_trial_field_created",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "Qualification",
    notes: "正式字段已切换到 replacement choice。旧字段 aigw_proposalcontent 保留但不参与 Select/Form/View/Safe Context。",
  }),
  field({
    appName: "estimatedQuoteBand",
    sourceLabel: "预计报价金额",
    companyLogicalName: "new_estimated_quote_amount",
    trialLogicalName: "aigw_estimatedquoteamount",
    d365Name: "aigw_estimatedquoteamount",
    label: labels("预计报价金额", "Estimated Quote Amount", "見積金額"),
    type: "currency",
    targetObject: "Quote",
    category: "quote",
    crmDataKey: "exact_revenue",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "band",
    requiredForDemo: true,
    sourcePage: "Quote / Forecast",
  }),
  field({
    appName: "wonReasonSummary",
    sourceLabel: "受注理由",
    companyLogicalName: null,
    trialLogicalName: "aigw_wonreason",
    d365Name: "aigw_wonreason",
    label: labels("受注理由", "Won Reason", "受注理由"),
    type: "multiline",
    targetObject: "Opportunity",
    category: "salesProgress",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
  }),
  field({
    appName: "lostReasonSummary",
    sourceLabel: "失注理由",
    companyLogicalName: null,
    trialLogicalName: "aigw_lostreason",
    d365Name: "aigw_lostreason",
    label: labels("失注理由", "Lost Reason", "失注理由"),
    type: "multiline",
    targetObject: "Opportunity",
    category: "salesProgress",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
  }),
  field({
    appName: "expectedOrderStatus",
    sourceLabel: "预计下单日",
    companyLogicalName: "estimatedclosedate",
    trialLogicalName: "estimatedclosedate",
    d365Name: "estimatedclosedate",
    label: labels("预计下单日", "Expected Order Date", "受注予定日"),
    type: "date",
    targetObject: "Opportunity",
    category: "quote",
    crmDataKey: "expected_order_date",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "relativeDate",
    requiredForDemo: true,
    sourcePage: "Quote / Forecast",
  }),
  field({
    appName: "budgetAmountBand",
    sourceLabel: "预算金额",
    companyLogicalName: "estimatedvalue",
    trialLogicalName: "estimatedvalue",
    d365Name: "estimatedvalue",
    label: labels("预算金额", "Budget Amount", "予算金額"),
    type: "currency",
    targetObject: "Opportunity",
    category: "quote",
    crmDataKey: "budget_amount",
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "band",
    requiredForDemo: true,
    sourcePage: "Quote / Forecast",
  }),
  field({
    appName: "winProbability",
    sourceLabel: "受注确度",
    companyLogicalName: "new_capability",
    trialLogicalName: "aigw_winprobabilityrank",
    d365Name: "aigw_winprobabilityrank",
    label: labels("受注确度", "Win Probability Rank", "受注確度"),
    type: "choice",
    targetObject: "Opportunity",
    category: "salesProgress",
    crmDataKey: "win_probability",
    choiceOptions: winProbabilityOptions,
    includeInSelect: true,
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "Sales Progress",
    notes: "Z>A>B>C>D>Y，Y 为最低确认度。",
  }),
  field({
    appName: "timelineSummary",
    sourceLabel: "Timeline / 跟进记录",
    companyLogicalName: null,
    trialLogicalName: null,
    d365Name: null,
    label: labels("跟进摘要", "Timeline Summary", "活動要約"),
    type: "multiline",
    targetObject: "Activity",
    category: "activity",
    crmDataKey: "timeline_text",
    sourceSystem: "ai_gateway",
    mappingStatus: "derived",
    realLogicalNameConfirmed: confirmed(false),
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "commercial_sensitive",
    safeTransform: "summarize",
    requiredForDemo: true,
    sourcePage: "AI Gateway",
    notes: "Raw Timeline 不进入 AI；只允许确定性脱敏摘要。",
  }),
  field({
    appName: "dataQualityFlags",
    sourceLabel: "数据质量标记",
    companyLogicalName: null,
    trialLogicalName: null,
    d365Name: null,
    label: labels("数据质量标记", "Data Quality Flags", "データ品質"),
    type: "textArray",
    targetObject: "Opportunity",
    category: "dataQuality",
    crmDataKey: "data_quality_flags",
    sourceSystem: "ai_gateway",
    mappingStatus: "derived",
    realLogicalNameConfirmed: confirmed(false),
    includeInCrmData: true,
    includeInSafeContext: true,
    sensitivity: "business",
    safeTransform: "keep",
    requiredForDemo: true,
    sourcePage: "AI Gateway",
  }),
];

export const salesTrialPhaseOneFields = opportunityFieldMapping.filter((field) => (
  field.includeInCrmData && field.sourceSystem === "sales_trial_d365"
));

export const replacementRequiredFields = opportunityFieldMapping.filter((field) => (
  field.mappingStatus === "needs_replacement"
));

export const legacyReplacedOpportunityFields = [
  legacyField("organizationGroup", "aigw_organizationgroup", "aigw_organizationgroup_choice"),
  legacyField("bookingDepartment", "aigw_bookingdepartment", "aigw_bookingdepartment_choice"),
  legacyField("salesDepartment", "aigw_salesdepartment", "aigw_salesdepartment_choice"),
  legacyField("priority", "aigw_priority", "aigw_priority_choice"),
  legacyField("researchBackground", "aigw_researchbackground", "aigw_researchbackground_choice"),
  legacyField("decisionMakerStatus", "aigw_decider", "aigw_decider_choice"),
  legacyField("customerNeed", "aigw_customerneed", "aigw_customerneed_choice"),
  legacyField("proposalContent", "aigw_proposalcontent", "aigw_proposalcontent_choice"),
  legacyField("opportunityList", "aigw_opportunitylist", "aigw_opportunitylist_bool"),
];

export const deferredOpportunityFields = opportunityFieldMapping.filter((field) => (
  !field.includeInCrmData && !field.requiredForDemo
));

export function requiredDemoFields(mapping = opportunityFieldMapping) {
  return mapping.filter((item) => item.requiredForDemo).map((item) => item.appName);
}

function field(options) {
  const isDerived = options.sourceSystem === "ai_gateway";
  const realLogicalNameConfirmed = options.realLogicalNameConfirmed || confirmed(Boolean(options.includeInSelect || options.d365Name && !String(options.d365Name).startsWith("aigw_")));

  return {
    d365Name: options.d365Name ?? options.trialLogicalName ?? null,
    appName: options.appName,
    label: options.label,
    type: options.type,
    companyType: options.companyType || options.type,
    trialType: options.trialType || options.type,
    targetObject: options.targetObject,
    category: options.category,
    companyLogicalName: options.companyLogicalName ?? null,
    trialLogicalName: options.trialLogicalName ?? null,
    sourceLabel: options.sourceLabel,
    sourceSystem: options.sourceSystem || (isDerived ? "ai_gateway" : "sales_trial_d365"),
    mappingStatus: options.mappingStatus || (isDerived ? "derived" : "active_after_trial_field_created"),
    realLogicalNameConfirmed,
    includeInSelect: Boolean(options.includeInSelect),
    includeInCrmData: Boolean(options.includeInCrmData),
    includeInSafeContext: Boolean(options.includeInSafeContext),
    sensitivity: options.sensitivity || "business",
    safeTransform: options.safeTransform || "exclude",
    requiredForDemo: Boolean(options.requiredForDemo),
    choiceOptions: options.choiceOptions || [],
    sourcePage: options.sourcePage || "Opportunity",
    confidence: options.confidence || "confirmed",
    notes: options.notes || "",
    crmDataKey: options.crmDataKey || options.appName,
    replacementTrialLogicalName: options.replacementTrialLogicalName || null,
    replacementType: options.replacementType || null,
  };
}

function legacyField(appName, oldTrialLogicalName, replacementTrialLogicalName) {
  return {
    appName,
    trialLogicalName: oldTrialLogicalName,
    d365Name: oldTrialLogicalName,
    sourceSystem: "sales_trial_d365",
    mappingStatus: "replaced_by_replacement",
    includeInSelect: false,
    includeInCrmData: false,
    includeInSafeContext: false,
    replacementTrialLogicalName,
  };
}
