import { randomUUID } from "node:crypto";

export function providerAuditMetadata({
  providerRequested = "demo",
  providerUsed = "demo",
  externalModelCalled = false,
  fallbackUsed = false,
  fallbackReason = "",
  safePayloadKeys = [],
  safePayloadCharCount = 0,
  responseCharCount = 0,
  durationMs = 0,
  timeoutMs = 20000,
  language = "zh-CN",
  outputGuardStatus = "not_applicable",
  blockedReason = "",
  responseFormatRequested = false,
  responseFormatRetryUsed = false,
  externalResponsePreviewSanitized = "",
  externalResponseParseError = "",
  blockedPatternKey = "",
} = {}) {
  return {
    provider_requested: providerRequested,
    provider_used: providerUsed,
    external_model_called: Boolean(externalModelCalled),
    fallback_used: Boolean(fallbackUsed),
    fallback_reason: fallbackReason,
    raw_data_sent: false,
    safe_context_used: true,
    safe_payload_keys: safePayloadKeys,
    safe_payload_char_count: safePayloadCharCount,
    response_char_count: responseCharCount,
    request_id: randomUUID(),
    duration_ms: durationMs,
    timeout_ms: timeoutMs,
    language,
    output_guard_status: outputGuardStatus,
    blocked_reason: blockedReason,
    response_format_requested: Boolean(responseFormatRequested),
    response_format_retry_used: Boolean(responseFormatRetryUsed),
    external_response_preview_sanitized: externalResponsePreviewSanitized,
    external_response_parse_error: externalResponseParseError,
    blocked_pattern_key: blockedPatternKey,
  };
}
